#!/usr/bin/env python3
"""Generate the first H18 adaptive one-erasure RTL laboratory.

The mathematical strategy is materialized directly from the exact H18-06
certificate. The generated controller:

* accepts A,B in the H17 packed 8-point permutation representation;
* checks raw PSL(2,7) membership once;
* evaluates only freely reduced query words of length <= 4;
* reuses one permutation-composition datapath and one H17 class engine;
* follows an exact identify-or-REJECT adaptive strategy;
* tolerates one persistent known query erasure without retrying that query.

This generator emits JSON, vectors, SystemVerilog and a short strategy summary.
The external modules psl27_membership_only and psl27_member_class_only are
generated by the H17 closure-classifier generator under the same methodology
used by H17-LAB-03.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve()
LAB = HERE.parents[1]
H18 = LAB.parent
CERT = H18 / "certificates" / "h18_adaptive_one_erasure_certificate.py"

spec = importlib.util.spec_from_file_location("h18e", CERT)
assert spec is not None and spec.loader is not None
h18e = importlib.util.module_from_spec(spec)
spec.loader.exec_module(h18e)

h17 = h18e.h17
QUERIES = h18e.QUERIES
QUERY_MASKS = h18e.QUERY_MASKS
CLASS_NAMES = h18e.CLASS_NAMES
ALL_MASK = h18e.ALL_MASK
REPS = h18e.REPS
IS_GENERATING = h18e.IS_GENERATING

GEN_ID = {rep: i for i, rep in enumerate(h17.REPS)}
LETTER_CODE = {"A": 0, "B": 1, "a": 2, "b": 3}


def popcount(mask: int) -> int:
    return mask.bit_count()


def terminal_label(mask: int):
    assert h18e.terminal(mask)
    gen_states = [
        i for i in range(len(REPS))
        if ((mask >> i) & 1) and IS_GENERATING[i]
    ]
    if not gen_states:
        return ("REJECT", 127)
    assert len(gen_states) == 1
    state = gen_states[0]
    return ("ORBIT", GEN_ID[REPS[state]])


def query_parts(mask: int, qi: int):
    return [
        (cls, mask & class_mask)
        for cls, class_mask in enumerate(QUERY_MASKS[qi])
        if mask & class_mask
    ]


def choose_no(mask: int, successful_left: int, banned_query: int) -> int:
    assert not h18e.terminal(mask)
    candidates = []
    for qi, (word, _, _) in enumerate(QUERIES):
        if qi == banned_query:
            continue
        parts = query_parts(mask, qi)
        if len(parts) <= 1:
            continue
        if all(
            h18e.no_erasure(part, successful_left - 1, banned_query)
            for _, part in parts
        ):
            candidates.append((
                max(popcount(part) for _, part in parts),
                -len(parts), len(word), word, qi
            ))
    if not candidates:
        raise AssertionError((
            "no post-erasure strategy",
            popcount(mask),
            successful_left,
            banned_query,
        ))
    candidates.sort()
    return candidates[0][-1]


def choose_one(mask: int, successful_left: int) -> int:
    assert not h18e.terminal(mask)
    candidates = []
    for qi, (word, _, _) in enumerate(QUERIES):
        parts = query_parts(mask, qi)
        if len(parts) <= 1:
            continue
        if not h18e.no_erasure(mask, successful_left, qi):
            continue
        if not all(
            h18e.one_erasure(part, successful_left - 1)
            for _, part in parts
        ):
            continue
        candidates.append((
            max(popcount(part) for _, part in parts),
            -len(parts), len(word), word, qi
        ))
    if not candidates:
        raise AssertionError((
            "no pre-erasure strategy",
            popcount(mask),
            successful_left,
        ))
    candidates.sort()
    return candidates[0][-1]


class StrategyBuilder:
    def __init__(self):
        self.nodes = []
        self.memo = {}
        self.terminals = {}
        self.bad_id = self._terminal("FAULT", 127)

    def _reserve(self):
        node_id = len(self.nodes)
        self.nodes.append(None)
        return node_id

    def _terminal(self, kind, orbit):
        key = (kind, orbit)
        if key in self.terminals:
            return self.terminals[key]
        node_id = self._reserve()
        self.nodes[node_id] = {
            "id": node_id,
            "kind": kind,
            "orbit_id": orbit,
        }
        self.terminals[key] = node_id
        return node_id

    def build(
        self,
        phase: str,
        mask: int,
        successful_left: int,
        banned_query: int = -1,
    ):
        if h18e.terminal(mask):
            kind, orbit = terminal_label(mask)
            return self._terminal(kind, orbit)

        key = (phase, mask, successful_left, banned_query)
        if key in self.memo:
            return self.memo[key]

        node_id = self._reserve()
        self.memo[key] = node_id

        if phase == "ONE":
            qi = choose_one(mask, successful_left)
            erase_next = self.build("NO", mask, successful_left, qi)
            can_erase = True
        else:
            qi = choose_no(mask, successful_left, banned_query)
            erase_next = self.bad_id
            can_erase = False

        class_next = [self.bad_id] * 6
        for cls, part in query_parts(mask, qi):
            if phase == "ONE":
                class_next[cls] = self.build(
                    "ONE", part, successful_left - 1
                )
            else:
                class_next[cls] = self.build(
                    "NO", part, successful_left - 1, banned_query
                )

        word = QUERIES[qi][0]
        self.nodes[node_id] = {
            "id": node_id,
            "kind": "QUERY",
            "phase": phase,
            "state_count": popcount(mask),
            "successful_left": successful_left,
            "banned_query": banned_query,
            "query_index": qi,
            "word": word,
            "aliases": list(QUERIES[qi][2]),
            "can_erase": can_erase,
            "erase_next": erase_next,
            "class_next": class_next,
        }
        return node_id


def encode_word(word: str):
    code = 0
    for i, ch in enumerate(word):
        code |= LETTER_CODE[ch] << (2 * i)
    return len(word), code


def pack_perm(p):
    value = 0
    for i, image in enumerate(p):
        value |= image << (3 * i)
    return value


def summarize(builder: StrategyBuilder, root: int):
    kinds = Counter(node["kind"] for node in builder.nodes)
    qnodes = [n for n in builder.nodes if n["kind"] == "QUERY"]
    distinct_words = sorted(
        {n["word"] for n in qnodes},
        key=lambda w: (len(w), w),
    )
    phase_counts = Counter(n.get("phase", "") for n in qnodes)
    return {
        "root_node": root,
        "total_nodes": len(builder.nodes),
        "query_nodes": len(qnodes),
        "terminal_orbit_nodes": kinds["ORBIT"],
        "terminal_reject_nodes": kinds["REJECT"],
        "terminal_fault_nodes": kinds["FAULT"],
        "pre_erasure_query_nodes": phase_counts["ONE"],
        "post_erasure_query_nodes": phase_counts["NO"],
        "distinct_query_words": distinct_words,
        "distinct_query_word_count": len(distinct_words),
        "max_word_length": max(map(len, distinct_words)),
    }


def emit_json(path: Path, builder: StrategyBuilder, root: int):
    summary = summarize(builder, root)
    payload = {
        "contract": {
            "state_space": "197 simultaneous-conjugacy pair orbits",
            "outputs": "114 orbit IDs or REJECT",
            "fault_model": (
                "at most one persistent known query erasure; "
                "erased query is not retried"
            ),
            "successful_query_bound": 4,
            "total_attempt_bound": 5,
            "word_length_bound": 4,
        },
        "summary": summary,
        "root": root,
        "nodes": builder.nodes,
    }
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return summary


def emit_vectors(path: Path):
    lines = ["# A B expected_status expected_orbit_id"]
    for rep, is_gen in zip(REPS, IS_GENERATING):
        A, B = rep
        if is_gen:
            status = 2
            orbit = GEN_ID[rep]
        else:
            status = 1
            orbit = 127
        lines.append(
            f"{pack_perm(A):06x} {pack_perm(B):06x} "
            f"{status:x} {orbit:02x}"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def emit_sv(path: Path, builder: StrategyBuilder, root: int):
    node_count = len(builder.nodes)
    node_w = max(1, (node_count - 1).bit_length())
    bad_id = builder.bad_id

    lines = [
        "// Auto-generated by generate_h18_adaptive_rtl.py.",
        "// H18-06 adaptive identify-or-REJECT controller with one persistent erasure.",
        "module h18_adaptive_erasure_core(",
        "    input  logic        clk,",
        "    input  logic        rst,",
        "    input  logic        start,",
        "    input  logic [23:0] A_in,",
        "    input  logic [23:0] B_in,",
        "    input  logic        erase_now,",
        "    output logic        busy,",
        "    output logic        done,",
        "    output logic        query_pending,",
        "    output logic        input_valid,",
        "    output logic        identified,",
        "    output logic        rejected,",
        "    output logic [2:0]  status,",
        "    output logic [6:0]  orbit_id",
        ");",
        "",
        f"localparam integer NODE_W = {node_w};",
        f"localparam [NODE_W-1:0] ROOT_NODE = {root};",
        f"localparam [NODE_W-1:0] BAD_NODE = {bad_id};",
        "localparam [2:0]",
        "    ST_IDLE=3'd0, ST_CHECK=3'd1, ST_DISPATCH=3'd2,",
        "    ST_WORD=3'd3, ST_CLASSIFY=3'd4, ST_DONE=3'd5;",
        "localparam [1:0]",
        "    NK_QUERY=2'd0, NK_ORBIT=2'd1,",
        "    NK_REJECT=2'd2, NK_FAULT=2'd3;",
        "",
        "logic [2:0] state;",
        "logic [23:0] A_reg, B_reg, invA_reg, invB_reg;",
        "logic valid_A, valid_B;",
        "logic [NODE_W-1:0] node_id, class_next, erase_next;",
        "logic [1:0] node_kind;",
        "logic [6:0] node_orbit;",
        "logic node_can_erase;",
        "logic [2:0] node_word_len;",
        "logic [7:0] node_word_code;",
        "logic [2:0] word_pos;",
        "logic [23:0] word_acc, selected_perm, compose_result, class_perm;",
        "logic [1:0] selected_letter;",
        "logic [2:0] class_code;",
        "",
        "function automatic [2:0] getp(",
        "    input logic [23:0] p, input integer idx",
        ");",
        "    getp = p[idx*3 +: 3];",
        "endfunction",
        "",
        "function automatic [23:0] compose_perm(",
        "    input logic [23:0] p, input logic [23:0] q",
        ");",
        "    integer i;",
        "    logic [23:0] r;",
        "    logic [2:0] qi;",
        "    begin",
        "      r='0;",
        "      for(i=0;i<8;i=i+1) begin",
        "        qi=getp(q,i);",
        "        r[i*3 +:3]=getp(p,qi);",
        "      end",
        "      compose_perm=r;",
        "    end",
        "endfunction",
        "",
        "function automatic [23:0] inverse_perm(input logic [23:0] p);",
        "    integer i;",
        "    logic [23:0] r;",
        "    logic [2:0] pi;",
        "    begin",
        "      r='0;",
        "      for(i=0;i<8;i=i+1) begin",
        "        pi=getp(p,i);",
        "        r[pi*3 +:3]=i[2:0];",
        "      end",
        "      inverse_perm=r;",
        "    end",
        "endfunction",
        "",
        "psl27_membership_only u_mem_A(.perm(A_reg),.valid(valid_A));",
        "psl27_membership_only u_mem_B(.perm(B_reg),.valid(valid_B));",
        "psl27_member_class_only u_class(",
        "    .perm(class_perm),.class_code(class_code)",
        ");",
        "",
        "always @* begin",
        "    node_kind = NK_FAULT;",
        "    node_orbit = 7'h7f;",
        "    node_can_erase = 1'b0;",
        "    node_word_len = 3'd0;",
        "    node_word_code = 8'h00;",
        "    erase_next = BAD_NODE;",
        "    class_next = BAD_NODE;",
        "    case (node_id)",
    ]

    for node in builder.nodes:
        nid = node["id"]
        if node["kind"] == "QUERY":
            wlen, wcode = encode_word(node["word"])
            lines += [
                f"      {nid}: begin",
                "        node_kind = NK_QUERY;",
                f"        node_word_len = 3'd{wlen};",
                f"        node_word_code = 8'h{wcode:02x};",
                (
                    "        node_can_erase = 1'b"
                    + ("1;" if node["can_erase"] else "0;")
                ),
                f"        erase_next = {node['erase_next']};",
                "        case (class_code)",
            ]
            for cls, next_id in enumerate(node["class_next"]):
                lines.append(
                    f"          3'd{cls}: class_next = {next_id};"
                )
            lines += [
                "          default: class_next = BAD_NODE;",
                "        endcase",
                "      end",
            ]
        elif node["kind"] == "ORBIT":
            lines += [
                (
                    f"      {nid}: begin "
                    f"node_kind=NK_ORBIT; "
                    f"node_orbit=7'd{node['orbit_id']}; end"
                )
            ]
        elif node["kind"] == "REJECT":
            lines += [
                f"      {nid}: begin node_kind=NK_REJECT; end"
            ]
        else:
            lines += [
                f"      {nid}: begin node_kind=NK_FAULT; end"
            ]

    lines += [
        "      default: begin node_kind=NK_FAULT; end",
        "    endcase",
        "end",
        "",
        "always @* begin",
        "    case (word_pos)",
        "      3'd0: selected_letter = node_word_code[1:0];",
        "      3'd1: selected_letter = node_word_code[3:2];",
        "      3'd2: selected_letter = node_word_code[5:4];",
        "      default: selected_letter = node_word_code[7:6];",
        "    endcase",
        "    case (selected_letter)",
        "      2'd0: selected_perm = A_reg;",
        "      2'd1: selected_perm = B_reg;",
        "      2'd2: selected_perm = invA_reg;",
        "      default: selected_perm = invB_reg;",
        "    endcase",
        "    compose_result = compose_perm(word_acc, selected_perm);",
        "end",
        "",
        "assign query_pending = (state == ST_CLASSIFY);",
        "",
        "always_ff @(posedge clk) begin",
        "  if (rst) begin",
        "    state<=ST_IDLE;",
        "    busy<=1'b0;",
        "    done<=1'b0;",
        "    input_valid<=1'b0;",
        "    identified<=1'b0;",
        "    rejected<=1'b0;",
        "    status<=3'd0;",
        "    orbit_id<=7'h7f;",
        "    A_reg<=0;",
        "    B_reg<=0;",
        "    invA_reg<=0;",
        "    invB_reg<=0;",
        "    node_id<=ROOT_NODE;",
        "    word_pos<=0;",
        "    word_acc<=24'hfac688;",
        "    class_perm<=24'hfac688;",
        "  end else begin",
        "    done <= 1'b0;",
        "    case (state)",
        "      ST_IDLE: begin",
        "        busy<=1'b0;",
        "        if(start) begin",
        "          A_reg<=A_in;",
        "          B_reg<=B_in;",
        "          invA_reg<=inverse_perm(A_in);",
        "          invB_reg<=inverse_perm(B_in);",
        "          input_valid<=1'b0;",
        "          identified<=1'b0;",
        "          rejected<=1'b0;",
        "          status<=3'd0;",
        "          orbit_id<=7'h7f;",
        "          node_id<=ROOT_NODE;",
        "          busy<=1'b1;",
        "          state<=ST_CHECK;",
        "        end",
        "      end",
        "      ST_CHECK: begin",
        "        input_valid <= valid_A & valid_B;",
        "        if(!(valid_A & valid_B)) begin",
        "          status<=3'd0;",
        "          state<=ST_DONE;",
        "        end else begin",
        "          node_id<=ROOT_NODE;",
        "          state<=ST_DISPATCH;",
        "        end",
        "      end",
        "      ST_DISPATCH: begin",
        "        case(node_kind)",
        "          NK_QUERY: begin",
        "            word_acc<=24'hfac688;",
        "            word_pos<=3'd0;",
        "            state<=ST_WORD;",
        "          end",
        "          NK_ORBIT: begin",
        "            identified<=1'b1;",
        "            rejected<=1'b0;",
        "            status<=3'd2;",
        "            orbit_id<=node_orbit;",
        "            state<=ST_DONE;",
        "          end",
        "          NK_REJECT: begin",
        "            identified<=1'b0;",
        "            rejected<=1'b1;",
        "            status<=3'd1;",
        "            orbit_id<=7'h7f;",
        "            state<=ST_DONE;",
        "          end",
        "          default: begin",
        "            status<=3'd4;",
        "            orbit_id<=7'h7f;",
        "            state<=ST_DONE;",
        "          end",
        "        endcase",
        "      end",
        "      ST_WORD: begin",
        "        word_acc <= compose_result;",
        "        if(word_pos + 3'd1 >= node_word_len) begin",
        "          class_perm <= compose_result;",
        "          state<=ST_CLASSIFY;",
        "        end else begin",
        "          word_pos <= word_pos + 3'd1;",
        "        end",
        "      end",
        "      ST_CLASSIFY: begin",
        "        if(erase_now) begin",
        "          if(node_can_erase) begin",
        "            node_id<=erase_next;",
        "            state<=ST_DISPATCH;",
        "          end else begin",
        "            status<=3'd4;",
        "            orbit_id<=7'h7f;",
        "            state<=ST_DONE;",
        "          end",
        "        end else begin",
        "          node_id<=class_next;",
        "          state<=ST_DISPATCH;",
        "        end",
        "      end",
        "      ST_DONE: begin",
        "        busy<=1'b0;",
        "        done<=1'b1;",
        "        state<=ST_IDLE;",
        "      end",
        "      default: begin",
        "        status<=3'd4;",
        "        busy<=1'b0;",
        "        state<=ST_IDLE;",
        "      end",
        "    endcase",
        "  end",
        "end",
        "endmodule",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def emit_tb(path: Path):
    path.write_text(r'''module tb_h18_adaptive_erasure;
logic clk,rst,start,erase_now;
logic [23:0] A_in,B_in;
logic busy,done,query_pending,input_valid,identified,rejected;
logic [2:0] status;
logic [6:0] orbit_id;

h18_adaptive_erasure_core dut(
 .clk(clk),.rst(rst),.start(start),.A_in(A_in),.B_in(B_in),
 .erase_now(erase_now),.busy(busy),.done(done),
 .query_pending(query_pending),.input_valid(input_valid),
 .identified(identified),.rejected(rejected),
 .status(status),.orbit_id(orbit_id)
);

always #5 clk=~clk;

integer fd,rc,n,attempts,cycles,max_cycles,max_attempts,total_runs;
reg [1023:0] file_name;
reg [23:0] ea,eb;
reg [3:0] es;
reg [7:0] eoid;

task automatic run_case(input integer target);
integer fired;
begin
  @(negedge clk);
  A_in=ea; B_in=eb; start=1'b1; erase_now=1'b0;
  @(negedge clk);
  start=1'b0;
  attempts=0; cycles=0; fired=0;

  while(!done && cycles<120) begin
    @(negedge clk);
    erase_now=1'b0;
    if(query_pending) begin
      attempts=attempts+1;
      if(target>0 && attempts==target && !fired) begin
        erase_now=1'b1;
        fired=1;
      end
    end
    cycles=cycles+1;
  end
  erase_now=1'b0;

  if(!done)
    $fatal(1,"timeout vector=%0d erase_target=%0d",n,target);

  if(cycles>max_cycles) max_cycles=cycles;
  if(attempts>max_attempts) max_attempts=attempts;

  if(status!==es[2:0] || orbit_id!==eoid[6:0])
    $fatal(1,
      "mismatch vector=%0d erase_target=%0d A=%h B=%h expected status=%h orbit=%h got status=%h orbit=%h attempts=%0d cycles=%0d",
      n,target,ea,eb,es,eoid,status,orbit_id,attempts,cycles);

  if(es==4'h2 && (!identified || rejected))
    $fatal(1,"success flags mismatch vector=%0d",n);

  if(es==4'h1 && (!rejected || identified))
    $fatal(1,"reject flags mismatch vector=%0d",n);

  if(attempts>5)
    $fatal(1,
      "attempt bound exceeded vector=%0d target=%0d attempts=%0d",
      n,target,attempts);

  total_runs=total_runs+1;
end
endtask

initial begin
  clk=0; rst=1; start=0; erase_now=0; A_in=0; B_in=0;
  n=0; max_cycles=0; max_attempts=0; total_runs=0;

  repeat(3) @(negedge clk);
  rst=0;

  if(!$value$plusargs("VECTORS=%s",file_name))
    file_name="generated/h18_adaptive_vectors.txt";

  fd=$fopen(file_name,"r");
  if(!fd) $fatal(1,"vectors missing: %0s",file_name);

  rc=$fgets(file_name,fd);

  while(!$feof(fd)) begin
    rc=$fscanf(fd,"%h %h %h %h\n",ea,eb,es,eoid);
    if(rc==4) begin
      run_case(0);
      run_case(1);
      run_case(2);
      run_case(3);
      run_case(4);
      n=n+1;
      if((n%25)==0)
        $display(
          "PROGRESS H18-LAB-01: states=%0d runs=%0d max_attempts=%0d max_cycles=%0d",
          n,total_runs,max_attempts,max_cycles);
    end
  end

  $fclose(fd);
  $display(
    "PASS H18-LAB-01 adaptive RTL: %0d states x 5 schedules = %0d runs; max_attempts=%0d max_cycles=%0d",
    n,total_runs,max_attempts,max_cycles);
  $finish;
end
endmodule
''', encoding="utf-8")


def emit_summary(path: Path, summary):
    words = ", ".join(summary["distinct_query_words"])
    path.write_text(
        "# H18-LAB-01 generated strategy summary\n\n"
        f"- root node: {summary['root_node']}\n"
        f"- total controller nodes: {summary['total_nodes']}\n"
        f"- query nodes: {summary['query_nodes']}\n"
        f"- pre-erasure query nodes: {summary['pre_erasure_query_nodes']}\n"
        f"- post-erasure query nodes: {summary['post_erasure_query_nodes']}\n"
        f"- orbit terminals: {summary['terminal_orbit_nodes']}\n"
        f"- REJECT terminals: {summary['terminal_reject_nodes']}\n"
        f"- FAULT terminals: {summary['terminal_fault_nodes']}\n"
        f"- distinct query words: {summary['distinct_query_word_count']}\n"
        f"- max word length: {summary['max_word_length']}\n\n"
        f"Words: {words}\n",
        encoding="utf-8",
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default=str(LAB / "generated"))
    args = ap.parse_args()
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    assert h18e.one_erasure(ALL_MASK, 3) is False
    assert h18e.one_erasure(ALL_MASK, 4) is True

    builder = StrategyBuilder()
    root = builder.build("ONE", ALL_MASK, 4)

    summary = emit_json(
        out / "h18_adaptive_strategy.json",
        builder,
        root,
    )
    emit_vectors(out / "h18_adaptive_vectors.txt")
    emit_sv(out / "h18_adaptive_erasure_core.sv", builder, root)
    emit_tb(out / "tb_h18_adaptive_erasure.sv")
    emit_summary(
        out / "H18_ADAPTIVE_STRATEGY_SUMMARY.md",
        summary,
    )

    print("HATTER-SOL-18 H18-LAB-01 adaptive RTL generator")
    for key, value in summary.items():
        print(key, "=", value)
    print(
        "PASS: exact H18-06 strategy materialized as "
        "JSON, vectors and SystemVerilog"
    )


if __name__ == "__main__":
    main()
