#!/usr/bin/env python3
"""HATTER-SOL-18 H18-03: Higman/trace-lift certificate for the 32+32 split.

This exact finite certificate works in the canonical H17 PSL(2,7) model.

For a projective pair (A,B) in PSL(2,7)^2 choose arbitrary determinant-one
matrix lifts A~, B~ in SL(2,7).  The commutator

    [A~,B~] = A~ B~ A~^-1 B~^-1

is independent of changing either lift by -I.  Therefore its trace

    tau(A,B) = tr([A~,B~]) in F_7

is a canonical invariant of the projective pair.

The script verifies:
  * tau takes exactly the values 3,4,5,6 on the 114 generating orbit states;
  * fiber sizes are 32,32,14,36 respectively;
  * the Nielsen graph generated by swap, invA and A->AB has exactly one
    connected component in each tau fiber;
  * tau=3 and tau=4 both project to PSL commutator class 4A, explaining the
    previously unresolved 32+32 split;
  * tau=6 corresponds to 3A;
  * tau=5 corresponds to the extended order-7 sector 7A/7B;
  * the nontrivial outer automorphism induced by PGL(2,7) preserves tau and
    acts without fixed vertices on the 114 inner-conjugacy orbit states,
    halving the four component sizes to 18,16,16,7.

No floating point arithmetic is used.
"""

from __future__ import annotations

import importlib.util
from collections import Counter, deque
from itertools import product
from pathlib import Path

P = 7
HERE = Path(__file__).resolve()
H18 = HERE.parents[1]
HATTER = H18.parent
H17_MODEL = HATTER / "17-NONABELIAN-TOMOGRAPHY-HARDWARE" / "tools" / "generate_psl27_golden_model.py"

spec = importlib.util.spec_from_file_location("h17_golden", H17_MODEL)
assert spec is not None and spec.loader is not None
h17 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(h17)

G = h17.G
INV = h17.INV
REPS = h17.REPS
REP_ID = {rep: i for i, rep in enumerate(REPS)}
ID = h17.ID

def mmul(m, n):
    a,b,c,d = m
    e,f,g,h = n
    return (
        (a*e+b*g) % P,
        (a*f+b*h) % P,
        (c*e+d*g) % P,
        (c*f+d*h) % P,
    )

def minv(m):
    a,b,c,d = m
    return (d % P, (-b) % P, (-c) % P, a % P)

def mcomm(a, b):
    return mmul(mmul(mmul(a,b), minv(a)), minv(b))

def mtrace(m):
    return (m[0] + m[3]) % P

def build_sl_lifts():
    lifts = {}
    for a,b,c,d in product(range(P), repeat=4):
        if (a*d-b*c) % P != 1:
            continue
        perm = h17.mobius_perm(a,b,c,d)
        lifts.setdefault(perm, []).append((a,b,c,d))
    assert len(lifts) == 168
    assert {len(v) for v in lifts.values()} == {2}
    for perm, mats in lifts.items():
        x = mats[0]
        minus_x = tuple((-v) % P for v in x)
        assert minus_x in mats
        assert h17.mobius_perm(*minus_x) == perm
    return lifts

SL_LIFTS = build_sl_lifts()

def tau(a, b):
    # Arbitrary choice is safe: replacing either lift by -I leaves the
    # commutator unchanged exactly, not merely projectively.
    A = SL_LIFTS[a][0]
    B = SL_LIFTS[b][0]
    t0 = mtrace(mcomm(A,B))
    for A2 in SL_LIFTS[a]:
        for B2 in SL_LIFTS[b]:
            assert mtrace(mcomm(A2,B2)) == t0
    return t0

def psl_commutator(a, b):
    return h17.compose(h17.compose(h17.compose(a,b), INV[a]), INV[b])

def orbit_id(a, b):
    rep = min((h17.conjugate(g,a), h17.conjugate(g,b)) for g in G)
    return REP_ID[rep]

def move_permutation(move):
    out = [orbit_id(*move(a,b)) for a,b in REPS]
    assert sorted(out) == list(range(114))
    return tuple(out)

MOVES = {
    "swap": lambda a,b: (b,a),
    "invA": lambda a,b: (INV[a],b),
    "A_to_AB": lambda a,b: (h17.compose(a,b),b),
}

def graph_components():
    adj = [set() for _ in range(114)]
    for move in MOVES.values():
        perm = move_permutation(move)
        for i,j in enumerate(perm):
            adj[i].add(j)
            adj[j].add(i)
    seen = set()
    comps = []
    for start in range(114):
        if start in seen:
            continue
        q = deque([start])
        seen.add(start)
        comp = []
        while q:
            x = q.popleft()
            comp.append(x)
            for y in adj[x]:
                if y not in seen:
                    seen.add(y)
                    q.append(y)
        comps.append(sorted(comp))
    return comps

def inverse_perm(p):
    out = [0] * len(p)
    for i,j in enumerate(p):
        out[j] = i
    return tuple(out)

def mobius_perm_general(a,b,c,d):
    out = []
    for x in range(P):
        den = (c*x+d) % P
        num = (a*x+b) % P
        out.append(h17.INF if den == 0 else (num * h17.invmod(den)) % P)
    out.append(h17.INF if c % P == 0 else (a * h17.invmod(c)) % P)
    return tuple(out)

def cycle_distribution(perm):
    seen = set()
    out = Counter()
    for s in range(len(perm)):
        if s in seen:
            continue
        x = s
        n = 0
        while x not in seen:
            seen.add(x)
            n += 1
            x = perm[x]
        out[n] += 1
    return dict(sorted(out.items()))

def main():
    assert len(REPS) == 114

    taus = [tau(a,b) for a,b in REPS]
    tau_counts = dict(sorted(Counter(taus).items()))
    assert tau_counts == {3:32, 4:32, 5:14, 6:36}

    psl_classes = [h17.CLASS_OF[psl_commutator(a,b)] for a,b in REPS]
    by_tau_classes = {
        t: dict(sorted(Counter(psl_classes[i] for i,v in enumerate(taus) if v == t).items()))
        for t in sorted(set(taus))
    }
    assert by_tau_classes[3] == {"4A":32}
    assert by_tau_classes[4] == {"4A":32}
    assert by_tau_classes[5] == {"7A":7, "7B":7}
    assert by_tau_classes[6] == {"3A":36}

    comps = graph_components()
    assert sorted(map(len, comps), reverse=True) == [36,32,32,14]

    comp_taus = []
    for comp in comps:
        values = {taus[i] for i in comp}
        assert len(values) == 1
        comp_taus.append((next(iter(values)), len(comp)))
    assert sorted(comp_taus) == [(3,32),(4,32),(5,14),(6,36)]

    # Each trace fiber is one connected component.
    for t,count in tau_counts.items():
        fiber = {i for i,v in enumerate(taus) if v == t}
        hits = [set(c) for c in comps if c and taus[c[0]] == t]
        assert len(hits) == 1
        assert hits[0] == fiber
        assert len(fiber) == count

    # Nontrivial outer automorphism of PSL(2,7): conjugation by x -> 3x,
    # where det(diag(3,1))=3 is a nonsquare modulo 7.
    outer_h = mobius_perm_general(3,0,0,1)
    assert outer_h not in G
    outer_h_inv = inverse_perm(outer_h)

    def outer(g):
        y = h17.compose(h17.compose(outer_h,g), outer_h_inv)
        assert y in G
        return y

    outer_perm = tuple(orbit_id(outer(a),outer(b)) for a,b in REPS)
    assert sorted(outer_perm) == list(range(114))
    assert cycle_distribution(outer_perm) == {2:57}
    assert all(taus[i] == taus[outer_perm[i]] for i in range(114))

    quotient_sizes = {}
    for t in sorted(tau_counts):
        fiber = [i for i,v in enumerate(taus) if v == t]
        pairs = {tuple(sorted((i,outer_perm[i]))) for i in fiber}
        quotient_sizes[t] = len(pairs)
    assert quotient_sizes == {3:16,4:16,5:7,6:18}

    print("HATTER-SOL-18 H18-03 Higman/trace-lift certificate")
    print("canonical H17 orbit states = 114")
    print("trace invariant tau values and fiber sizes =", tau_counts)
    print("projective commutator classes by tau =", by_tau_classes)
    print("Nielsen components (tau,size) =", sorted(comp_taus))
    print("outer automorphism cycles =", cycle_distribution(outer_perm))
    print("Aut(PSL)-quotient sizes by tau =", quotient_sizes)
    print("KEY: the two 32-state 4A components are tau=3 and tau=4=-3")
    print("PASS: the 32+32 split is exactly the canonical SL(2,7) commutator-trace split")

if __name__ == "__main__":
    main()
