// HATTER-SOL-18 H18-07 sequential adaptive one-erasure processor.
//
// Board-independent reference RTL.
// The exact adaptive strategy is generated by generate_h18_adaptive_controller.py.
//
// erase_attempt_idx:
//   0     no injected erasure
//   1..5  erase that attempted query if the transaction reaches it
//
// status:
//   0 invalid raw A/B (not PSL(2,7))
//   1 valid PSL inputs, non-generating -> REJECT
//   2 generating orbit identified exactly
//   4 invalid/unreachable controller transition
//
// This is a simulation/architecture reference. No target FPGA timing claim.

module h18_adaptive_sequential_core(
    input  logic        clk,
    input  logic        rst,
    input  logic        start,
    input  logic [23:0] A_in,
    input  logic [23:0] B_in,
    input  logic [2:0]  erase_attempt_idx,

    output logic        busy,
    output logic        done,
    output logic [2:0]  status,
    output logic [6:0]  orbit_id,
    output logic [2:0]  attempts,
    output logic [2:0]  successes
);

localparam [3:0]
    ST_IDLE     = 4'd0,
    ST_CHECK    = 4'd1,
    ST_LOAD     = 4'd2,
    ST_WORD     = 4'd3,
    ST_CLASSIFY = 4'd4,
    ST_DONE     = 4'd5;

logic [3:0] state;
logic [23:0] A_reg, B_reg, invA_reg, invB_reg;
logic [2:0] erase_reg;

logic valid_A, valid_B;
logic [8:0] node_id;
logic [4:0] word_id;
logic erasure_allowed;
logic [10:0] next_1A, next_2A, next_3A, next_4A, next_7A, next_7B, next_erased;
logic [2:0] word_len;
logic [7:0] word_ops;

logic [23:0] acc;
logic [2:0]  word_pos;
logic [23:0] class_perm;
logic [2:0]  class_code;

logic [1:0] symbol;
logic [23:0] symbol_perm;
logic [23:0] compose_result;
logic [10:0] selected_target;
logic inject_erasure;

function automatic [2:0] getp(input logic [23:0] p, input integer idx);
    getp = p[idx*3 +: 3];
endfunction

function automatic [23:0] compose_perm(input logic [23:0] p, input logic [23:0] q);
    integer i;
    logic [23:0] r;
    logic [2:0] qi;
    begin
      r='0;
      for(i=0;i<8;i=i+1) begin
        qi=getp(q,i);
        r[i*3 +: 3]=getp(p,qi);
      end
      compose_perm=r;
    end
endfunction

function automatic [23:0] inverse_perm(input logic [23:0] p);
    integer i;
    logic [23:0] r;
    logic [2:0] pi;
    begin
      r='0;
      for(i=0;i<8;i=i+1) begin
        pi=getp(p,i);
        r[pi*3 +: 3]=i[2:0];
      end
      inverse_perm=r;
    end
endfunction

psl27_membership_only u_mem_A(.perm(A_reg), .valid(valid_A));
psl27_membership_only u_mem_B(.perm(B_reg), .valid(valid_B));

psl27_member_class_only u_class(
    .perm(class_perm),
    .class_code(class_code)
);

h18_adaptive_controller_rom u_ctl(
    .node_id(node_id),
    .word_id(word_id),
    .erasure_allowed(erasure_allowed),
    .next_1A(next_1A), .next_2A(next_2A), .next_3A(next_3A),
    .next_4A(next_4A), .next_7A(next_7A), .next_7B(next_7B),
    .next_erased(next_erased)
);

h18_adaptive_word_rom u_words(
    .word_id(word_id),
    .word_len(word_len),
    .word_ops(word_ops)
);

always_comb begin
    symbol = (word_ops >> (word_pos*2)) & 2'b11;
    case (symbol)
      2'd0: symbol_perm = A_reg;
      2'd1: symbol_perm = invA_reg;
      2'd2: symbol_perm = B_reg;
      default: symbol_perm = invB_reg;
    endcase
    compose_result = compose_perm(acc, symbol_perm);

    case (class_code)
      3'd0: selected_target = next_1A;
      3'd1: selected_target = next_2A;
      3'd2: selected_target = next_3A;
      3'd3: selected_target = next_4A;
      3'd4: selected_target = next_7A;
      3'd5: selected_target = next_7B;
      default: selected_target = {2'd3,9'd0};
    endcase

    inject_erasure =
        (erase_reg != 0) &&
        ((attempts + 3'd1) == erase_reg);
end

task automatic apply_target(input logic [10:0] target);
    begin
      case (target[10:9])
        2'd0: begin
          node_id <= target[8:0];
          state <= ST_LOAD;
        end
        2'd1: begin
          orbit_id <= target[6:0];
          status <= 3'd2;
          state <= ST_DONE;
        end
        2'd2: begin
          orbit_id <= 7'h7f;
          status <= 3'd1;
          state <= ST_DONE;
        end
        default: begin
          orbit_id <= 7'h7f;
          status <= 3'd4;
          state <= ST_DONE;
        end
      endcase
    end
endtask

always_ff @(posedge clk) begin
    if (rst) begin
        state <= ST_IDLE;
        busy <= 1'b0;
        done <= 1'b0;
        status <= 3'd0;
        orbit_id <= 7'h7f;
        attempts <= 3'd0;
        successes <= 3'd0;
        A_reg <= 0;
        B_reg <= 0;
        invA_reg <= 0;
        invB_reg <= 0;
        erase_reg <= 0;
        node_id <= 0;
        acc <= 24'hfac688;
        word_pos <= 0;
        class_perm <= 24'hfac688;
    end else begin
        done <= 1'b0;

        case (state)
          ST_IDLE: begin
            busy <= 1'b0;
            if (start) begin
                A_reg <= A_in;
                B_reg <= B_in;
                invA_reg <= inverse_perm(A_in);
                invB_reg <= inverse_perm(B_in);
                erase_reg <= erase_attempt_idx;
                node_id <= 9'd0;
                attempts <= 3'd0;
                successes <= 3'd0;
                status <= 3'd0;
                orbit_id <= 7'h7f;
                busy <= 1'b1;
                state <= ST_CHECK;
            end
          end

          ST_CHECK: begin
            if (!(valid_A & valid_B)) begin
                status <= 3'd0;
                orbit_id <= 7'h7f;
                state <= ST_DONE;
            end else begin
                state <= ST_LOAD;
            end
          end

          ST_LOAD: begin
            acc <= 24'hfac688;
            word_pos <= 3'd0;
            attempts <= attempts + 3'd1;
            state <= ST_WORD;
          end

          ST_WORD: begin
            if (word_pos + 3'd1 == word_len) begin
                class_perm <= compose_result;
                state <= ST_CLASSIFY;
            end else begin
                acc <= compose_result;
                word_pos <= word_pos + 3'd1;
            end
          end

          ST_CLASSIFY: begin
            if (inject_erasure) begin
                if (erasure_allowed) begin
                    apply_target(next_erased);
                end else begin
                    status <= 3'd4;
                    orbit_id <= 7'h7f;
                    state <= ST_DONE;
                end
            end else begin
                successes <= successes + 3'd1;
                apply_target(selected_target);
            end
          end

          ST_DONE: begin
            busy <= 1'b0;
            done <= 1'b1;
            state <= ST_IDLE;
          end

          default: begin
            status <= 3'd4;
            orbit_id <= 7'h7f;
            state <= ST_DONE;
          end
        endcase
    end
end

endmodule
